spring:
  # DB 연결 - mysql workbench로 확인 가능
  datasource:
#    url: jdbc:mysql://localhost:3306/example?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: shinkong
#    driver-class-name: com.mysql.cj.jdbc.Driver
    # 설치된 H2 DB와 연결 url
    url: jdbc:h2:tcp://localhost/~/shinkong;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver  # 접속을 위한 드라이버


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
        use_sql_comments: true

  h2:
    console:
      enabled: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql

logging:
  level:
    org.hibernate.type: trace
    org.springframework: debug